#!/bin/bash

set -e

RELEASE_VERSION=$1
MDSBOT_ARTIFACTORY_APIKEY=$2
MDSBOT_ARTIFACTORY_USERNAME=$3
MAVEN_ARTIFACTORY_URL=$4
AWS_SECRET_ACCESS_KEY=$5
AWS_ACCESS_KEY_ID=$6
S3_BUCKET=$7

export RELEASE_VERSION=$RELEASE_VERSION
export MDSBOT_ARTIFACTORY_APIKEY=$MDSBOT_ARTIFACTORY_APIKEY
export MDSBOT_ARTIFACTORY_USERNAME=$MDSBOT_ARTIFACTORY_USERNAME
export MAVEN_ARTIFACTORY_URL=$MAVEN_ARTIFACTORY_URL
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export S3_BUCKET=$S3_BUCKET

ENVIRONMENT=dev

git checkout mds-${RELEASE_VERSION}

/bin/bash scripts/build.sh $ENVIRONMENT

./uploadUniverseToArtifactory.sh target/ $RELEASE_VERSION $ENVIRONMENT

./uploadUniverseToS3.sh $RELEASE_VERSION $S3_BUCKET $AWS_SECRET_ACCESS_KEY $AWS_ACCESS_KEY_ID
